### PR TITLE
Add solitaire game

### PR DESCRIPTION
**Pull request by mbillingr**
I just realized that there is a list of stuff made with ggez. So I thought I'd add a link to the [solitaire](https://github.com/Swampsoft/solitaire) game I wrote, if you'll have it.

Thank you for building an awesome framework in an awesome language! I am using it again in my next game project. :)

### CODE REVIEW

**Comment by icefoxen** [comment]
That looks fantastic!  I'll happily include it... unfortunately it doesn't compile on my machine!  I get piles of errors with `image` 0.19 not being able to compile.

Part of it is our fault for version bumping dependencies on a patch level update...  we recently discovered that counts as a breaking change and can have Irritating Effects.  Changing your `Cargo.toml` to explicitly specify `ggez = "=0.4.2"` causes a much smaller breakage on line 49 of `src/custom_audio.rs`, but that's easily fixed just by changing the `?` to `.unwrap()`.  With that, it works great!

It's weird, 'cause I'm going with the `Cargo.lock` that's in your repo.  :man_shrugging: 

Also, given that you apparently fought with ggez's audio a bit, have any input on what the API should look like to make it better?  It's on the list to rework for 0.5.

**Comment by mbillingr** [comment]
Thank you for the feedback! I just built a fresh clone of the repository without any issues. Which toolchain are you using? I am on 1.26.1... maybe I should update or try nightly?

The only request I'd have for the audio API is the ability to stop playing sounds. I ran into the problem that when dealing cards their sounds were queued and continued to play a long time after the animation was done. I simply hacked the audio code to replace the previous sound when starting a new one.

You may be interested in issue Swampsoft/solitaire#5, though. The hard coded font sizes I use are too large on my notebook in Linux, but they are fine on every other system I've seen. No idea what's going on, or maybe I'm just being ignorant of something fundamental...

**Comment by icefoxen** [comment]
Aha, I am using 1.27.0, though using 1.26.1 still causes the same problems.  Nightly shouldn't be necessary.

**Comment by mbillingr** [comment]
Updating the toolchain did not change anything on my side either. That is good :)

The error in line 49 of `custom_audio.rs` happens when ggez and my crate use different versions of Rodio. It should compile correctly with `ggez="0.4.3"` and `rodio="0.7"`, which are set in `Cargo.lock`.

The latest commit on *master* is [9c9fb0](https://github.com/Swampsoft/solitaire/commit/9c9fb0db2cd73d073b0326fb8e4dcc318e343c5b). It compiles fine, how ever I try to break it.
I guess (hope) that you somehow ended up using the wrong git head. My working fork `mbillingr/solitaire` is a few commits behind `Swampsoft/solitaire` and reproduces the compilation error when I run `cargo update` on it.

**Comment by icefoxen** [comment]
WHEW.  Okay.  That was WEIRD.  `image` 0.19 wouldn't compile at all for me.  All he versions were correct.  And then ggez failed compiling for the same reason.  Compiler changes made no difference.  So I ended up deleting the version of the `image` crate that cargo had fetched, re-fetched it... and huzzah, it all just worked!

So it works fine now, building from scratch.  Going to have to chalk this one up to cosmic rays or something.

**Comment by mbillingr** [comment]
How weird.
