### ISSUE TITLE
custom shaders using gfx_defines! broken with gfx version 0.18

### ISSUE THREAD

**Issue by Ben-PH** [ggez/ggez#595]
I copy-pasted `/examples/shader.rs`  into a fresh project, along with the shader files into `/resources` and went for a compile using latest gfx (0.18.0). This is the error I got:

```
error[E0277]: the trait bound `Dim: gfx::pso::buffer::Structure<(gfx_core::shade::BaseType, gfx_core::shade::ContainerType)>` is not satisfied
  --> src/main.rs:23:5
   |
23 |     shader: graphics::Shader<Dim>,
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `gfx::pso::buffer::Structure<(gfx_core::shade::BaseType, gfx_core::shade::ContainerType)>` is not implemented for `Dim`
   |
   = note: required by `ggez::graphics::ShaderGeneric`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.

```

Similar error for doing `shader.rs`

I checked `/examples/Cargo.toml`, noticed it's using `gfx = 0.17`

Digging around, I couldn't see where to get started. I'm in no way familiar with macros, so I wouldn't know where to start. The only thing that I saw changed, that I thought would be relevant was that docs were hidden above some macro definitions in `gfx`. I compiled local `0.18` with them removed. No change.

Compiled using latest ggez from git repo

**Comment by icefoxen** [comment]
This looks like a  version mismatch.  I recommend making *real sure* that you're using the same version of gfx everywhere; git master uses gfx 0.18.  gfx 0.18 is quite new and doesn't have many breaking API changes, so it's easy to get mixed up with previous versions, but though the compiler will think the types are named the same thing they are not interchangable.

...not sure what you're looking at though, since ggez doesn't have an `/examples/Cargo.toml` file.

I was able to run the `shaders.rs` example in a new project using the following deps in my `Cargo.toml`:

```toml
[dependencies]
ggez = "0.5.0-rc.1"
gfx = "0.18"
cgmath = {version = "0.17", features = ["mint"]}
```

**Comment by ducharmemp** [comment]
I had the same problem, forcing a `cargo clean` fixed the issue for me. I had an old version in my cargo-lock file.

**Comment by Ben-PH** [comment]
running a cargo clean and changing dependencies as recommended fixed the issue.
